version: "3.4"

services:
  payapi:
    image: payroll-api
    container_name: payroll-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3040:3040
