version: "3.4"

services:
  payapi:
    image: payroll-api
    container_name: payroll-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3040:3040
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
